CREATE TABLE IF NOT EXISTS followers (
  id INTEGER PRIMARY KEY,
  actor TEXT NOT NULL,
  uri TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS followers_actor_idx ON followers(actor COLLATE NOCASE);
CREATE UNIQUE INDEX IF NOT EXISTS followers_uri_idx ON followers(uri COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY,
  type TEXT NOT NULL,
  contents JSON NOT NULL,
  uri TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS posts_uri_idx ON posts(uri COLLATE NOCASE);
