DROP TABLE IF EXISTS followers;
CREATE TABLE followers (
  id INTEGER PRIMARY KEY,
  actor TEXT NOT NULL,
  uri TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX followers_actor_idx ON followers(actor COLLATE NOCASE);
CREATE UNIQUE INDEX followers_uri_idx ON followers(uri COLLATE NOCASE);

DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  type TEXT NOT NULL,
  contents JSON NOT NULL,
  uri TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX posts_uri_idx ON posts(uri COLLATE NOCASE);
