CREATE TABLE IF NOT EXISTS `followers` (
  `id` TEXT PRIMARY KEY,
  `actor` TEXT NOT NULL,
  `uri` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS `followers_actor_idx` ON `followers`(`actor` COLLATE NOCASE);
CREATE UNIQUE INDEX IF NOT EXISTS `followers_uri_idx` ON `followers`(`uri` COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS `following` (
  `id` TEXT PRIMARY KEY,
  `actor` INTEGER NOT NULL,
  `uri` TEXT NOT NULL,
  `confirmed` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS `following_actor_idx` ON `following`(`actor` COLLATE NOCASE);
CREATE UNIQUE INDEX IF NOT EXISTS `following_uri_idx` ON `following`(`uri` COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS `posts` (
  `id` TEXT PRIMARY KEY,
  `contents` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
